### PR TITLE
Remove the requirement for marking GDTaskPlayerLoopAutoload as autoload

### PR DESCRIPTION
**Pull request by Delsin-Yu**
This PR enables the GDTaskPlayerLoopAutoload to self-initialize when any GDTask API is called, removing the requirement for adding it as an autoload. For backward compatibility reasons, users may still add this script to the autoload list and let the engine load it instead.

### CODE REVIEW

**Comment by Delsin-Yu** [comment]
If this gets accepted, should we rename the `GDTaskPlayerLoopAutoload` and the `AutoLoad` folder? But I think that would break backward compatibility.

**Comment by Delsin-Yu** [comment]
This may also allow us to ship the addon as a plain managed class library through NuGet, which is more consistent with typical C# workflow.

**Review by felipemullen — APPROVED** [review]

**Comment by Atlinx** [comment]
@Delsin-Yu hey thanks for the PR! I've been busy with university work for the past few months so I haven't had the chance to look over your PR. I'll be sure to review it this weekend. Thanks again for your help :)

**Comment by Atlinx** [comment]
This looks good to merge. Thanks for your contribution! ❤️

**Pull request merged**
